# Taken from https://bugzilla.mozilla.org/show_bug.cgi?id=1665675#c2
diff --git a/build/moz.configure/init.configure b/build/moz.configure/init.configure
index 970ef849e5e9..bc74d1508c56 100644
--- a/build/moz.configure/init.configure
+++ b/build/moz.configure/init.configure
@@ -233,7 +233,7 @@ option(env='VIRTUALENV_NAME', nargs=1, default='init_py3',
 @imports('os')
 @imports('sys')
 @imports('subprocess')
-@imports('distutils.sysconfig')
+@imports(_from='distutils.sysconfig', _import='get_python_lib')
 @imports(_from='mozbuild.configure.util', _import='LineIO')
 @imports(_from='mozbuild.virtualenv', _import='VirtualenvManager')
 @imports(_from='mozbuild.virtualenv', _import='verify_python_version')
@@ -368,7 +368,7 @@ def virtualenv_python3(env_python, virtualenv_name, build_env, mozconfig, help):
         sys.exit(subprocess.call([python] + sys.argv))
 
     # We are now in the virtualenv
-    if not distutils.sysconfig.get_python_lib():
+    if not get_python_lib():
         die('Could not determine python site packages directory')
 
     str_version = '.'.join(str(v) for v in version)
